FROM centos
MAINTAINER lxg1208 (xuegang_1208@163.com)

#RUN mkdir /etc/yum.repos.d/bak && cd /etc/yum.repos.d/ && mv /etc/yum.repos.d/*.repo bak/ 
#ADD 163.repo /etc/yum.repos.d/163.repo 
#RUN yum clean all
RUN yum -y install supervisor

ENV TZ "Asia/Shanghai"
